language: cpp
os: linux
dist: bionic
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.1-bionic
  - sudo apt update

install:
  # C++17
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qy update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-8 gcc-8 -o Debug::pkgProblemResolver=yes; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90; fi
  # Qt5
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt514-meta-minimal; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export QMAKE=/opt/qt514/bin/qmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/opt/qt514/bin/:$PATH; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gcc --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then g++ --version; fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH; fi

  - $QMAKE -v
  - cd tests
  - git clone --depth 1 https://github.com/VioletGiraffe/cpp-template-utils
  - git clone --depth 1 https://github.com/VioletGiraffe/cpputils

script:
  # Building the main binaries
  - $QMAKE -r CONFIG+=release DEFINES+=TRAVIS_BUILD
  - make -j
  - pwd
  - ls
  - ls bin_tests/
  # Running tests
  - ./bin_tests/test-app
